A/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('home.urls', namespace='home')),
    path('products/', include('products.urls', namespace='products')),
    path('orders/', include('orders.urls', namespace='orders')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('verify/', views.UserRegisterVerifyCodeView.as_view(), name='verify_code'),
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('logout/', views.UserLogoutView.as_view(), name='user_logout'),
    path('profile/<int:user_id>', views.UserProfileView.as_view(), name='user_profile'),
]

orders/urls.py
from django.urls import path
from . import views


app_name = 'orders'
urlpatterns = [
    path('create/', views.OrderCreateView.as_view(), name='order_create'),
    path('detail/<int:order_id>/', views.OrderDetailView.as_view(), name='order_detail'),
    path('delete/<int:order_id>/', views.OrderDeleteView.as_view(), name='order_delete'),
    path('pay/<int:order_id>/', views.OrderPayView.as_view(), name='order_pay'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/add/<int:product_id>/', views.CartAddView.as_view(), name='cart_add'),
    path('cart/remove/<int:product_id>/', views.CartRemoveView.as_view(), name='cart_remove'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from .managers import UserManager


class User(AbstractBaseUser, PermissionsMixin):
    full_name = models.CharField(max_length=255)
    email = models.EmailField(max_length=255, unique=True)
    phone_number = models.CharField(max_length=11, unique=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'phone_number'
    REQUIRED_FIELDS = ['email', 'full_name']

    def __str__(self):
        return self.email

    @property
    def is_staff(self):
        return self.is_admin


class OtpCode(models.Model):
    phone_number = models.CharField(max_length=11, unique=True)
    code = models.PositiveSmallIntegerField()
    created = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.phone_number} - {self.code} - {self.created}'

accounts/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from .models import User


class UserCreationForm(forms.ModelForm):
    """
    A form for creating new users. Includes all the required fields, plus a repeated password.
    """

    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['full_name', 'email', 'phone_number']

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password1'] and cd['password2'] and cd['password1'] != cd['password2']:
            raise ValidationError("Passwords don't match")
        return cd['password2']

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password2'])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    """
    A form for updating users. Includes all the fields  the user,
    but replaces the password field with admin disabled password hash display field.
    """

    password = ReadOnlyPasswordHashField(help_text='you can change password with <a href=\"../password/\">this form</a>')

    class Meta:
        model = User
        fields = ['full_name', 'email', 'phone_number', 'password', 'last_login']


class UserRegisterForm(forms.Form):
    full_name = forms.CharField(
        label=False,
        widget=forms.TextInput({
            'class': 'form-control',
            'placeholder': 'Full Name',
        })
    )
    email = forms.EmailField(
        label=False,
        widget=forms.EmailInput({
            'class': 'form-control',
            'placeholder': 'Email',
        })
    )
    phone_number = forms.CharField(
        max_length=11,
        label=False,
        widget=forms.NumberInput({
            'class': 'form-control',
            'placeholder': 'Phone Number',
        })
    )
    password = forms.CharField(
        label=False,
        widget=forms.PasswordInput({
            'class': 'form-control',
            'placeholder': 'Password',
        })
    )

    def clean_email(self):
        email = self.cleaned_data['email']
        user = User.objects.filter(email=email).exists()
        if user:
            raise ValidationError('This email already exists!')
        return email

    def clean_phone_number(self):
        phone_number = self.cleaned_data['phone_number']
        user = User.objects.filter(phone_number=phone_number).exists()
        if user:
            raise ValidationError('This phone number already exists!')
        return phone_number


class UserRegisterVerifyCodeForm(forms.Form):
    code = forms.IntegerField(
        label=False,
        widget=forms.NumberInput({
            'class': 'form-control',
            'placeholder': 'Your Code',
        })
    )


class UserLoginForm(forms.Form):
    phone_number = forms.CharField(
        max_length=11,
        label=False,
        widget=forms.NumberInput({
            'class': 'form-control',
            'placeholder': 'Phone Number',
        })
    )
    password = forms.CharField(
        label=False,
        widget=forms.PasswordInput({
            'class': 'form-control',
            'placeholder': 'Password',
        })
    )

accounts/views.py
import random
import pytz
from datetime import datetime, timedelta
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from utils import otp_code
from .forms import UserRegisterForm, UserRegisterVerifyCodeForm, UserLoginForm
from .models import User, OtpCode


class UserRegisterView(View):
    form_class = UserRegisterForm
    template_name = 'accounts/register.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('home:home')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        form = self.form_class
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            random_code = random.randint(1000, 9999)  # Generate random code
            otp_code(cd['phone_number'], random_code)  # Send random code
            OtpCode.objects.create(phone_number=cd['phone_number'], code=random_code)
            request.session['user_register_info'] = {
                'full_name': cd['full_name'],
                'email': cd['email'],
                'phone_number': cd['phone_number'],
                'password': cd['password'],
            }
            return redirect('accounts:verify_code')
        return render(request, self.template_name, {'form': form})


class UserRegisterVerifyCodeView(View):
    form_class = UserRegisterVerifyCodeForm
    template_name = 'accounts/verify_code.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('home:home')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        form = self.form_class
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        user_session = request.session['user_register_info']
        code_instance = get_object_or_404(OtpCode, phone_number=user_session['phone_number'])
        if form.is_valid():
            if (datetime.now(tz=pytz.timezone('Asia/Tehran')) - code_instance.created) < timedelta(minutes=2):
                if form.cleaned_data['code'] == code_instance.code:
                    User.objects.create_user(
                        email=user_session['email'],
                        full_name=user_session['full_name'],
                        phone_number=user_session['phone_number'],
                        password=user_session['password']
                    )
                    code_instance.delete()
                    return redirect('home:home')
                else:
                    return redirect('accounts:verify_code')
            else:
                code_instance.delete()
                return redirect('accounts:user_register')
        return render(request, self.template_name, {'form': form})


class UserLoginView(View):
    form_class = UserLoginForm
    template_name = 'accounts/login.html'

    def setup(self, request, *args, **kwargs):
        self.next = request.GET.get('next')
        return super().setup(request, *args, **kwargs)

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('home:home')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        form = self.form_class
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(phone_number=cd['phone_number'], password=cd['password'])
            if user is not None:
                login(request, user)
                if self.next:
                    return redirect(self.next)
                return redirect('home:home')
            else:
                return redirect('accounts:user_login')
        return render(request, self.template_name, {'form': form})


class UserLogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        return redirect('home:home')


class UserProfileView(LoginRequiredMixin, View):
    def get(self, request, user_id):
        user = get_object_or_404(User, id=user_id)
        if request.user == user:
            user_order = user.orders.all()
            return render(request, 'accounts/profile.html', {'user': user, 'user_order': user_order})
        else:
            return redirect('home:home')

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="contact-section bg-light">
    <div class="hero-wrap hero-bread" style="background-image: url({% static 'images/bg_7.jpg' %});">
        <div class="container">
            <div class="row block-9 no-gutters align-items-center justify-content-center">
                <div class="col-md-9 ftco-animate text-center">
                    <h1 class="mb-0 bread">Login</h1><br><br>
                    <div class="col-md-12 order-md-last d-flex">
                        <form action="#" class=" p-5 contact-form" method="post" novalidate>
                            <div class="form-group">
                                {% csrf_token %}
                                {{ form.as_p }}
                            </div>
                            <div class="form-group">
                                <input type="submit" value="Login" class="btn btn-primary py-3 px-5">
                                <a href="{% url 'accounts:user_register' %}" class="btn btn-primary py-3 px-5">I don't have an account!</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="contact-section bg-light">
    <div class="hero-wrap hero-bread" style="background-image: url({% static 'images/bg_7.jpg' %});">
        <div class="container">
            <div class="row block-9 no-gutters align-items-center justify-content-center">
                <div class="col-md-9 ftco-animate text-center">
                    <h1 class="mb-0 bread">Profile</h1><br><br>
                    <div class="col-md-12 order-md-last d-flex">
                        <form action="#" class="bg-white p-4 contact-form">
                            <br>
                            <div class="form-group">
                                <p><span>Full Name :  </span><strong>{{ user.full_name }}</strong></p>
                            </div>
                            <hr>
                            <div class="form-group">
                                <p><span>Email :  </span><strong>{{ user.email }}</strong></p>
                            </div>
                            <hr>
                            <div class="form-group">
                                <p><span>Phone Number :  </span><strong>{{ user.phone_number }}</strong></p>
                            </div>
                            <hr>
                            <div class="form-group">
                                {% for item in user_order %}
                                <p class="mr-4">
                                    <a href="{% url 'orders:order_delete' item.id %}" class="{% if item.paid %} disable {% else %} btn btn-danger ion-ios-close {% endif %}"></a>
                                    <a href="{% if item.paid %} # {% else %} {% url 'orders:order_detail' item.id %} {% endif %}">{{ item.get_name_item }} </a><span>Paid : </span><span class="{% if item.paid %} icon-check {% else %} icon-check-minus {% endif %}"></span>
                                </p>
                                <hr>
                                {% endfor %}
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="contact-section bg-light">
    <div class="hero-wrap hero-bread" style="background-image: url({% static 'images/bg_7.jpg' %});">
        <div class="container">
            <div class="row block-9 no-gutters align-items-center justify-content-center">
                <div class="col-md-9 ftco-animate text-center">
                    <h1 class="mb-0 bread">Register</h1><br><br>
                    <div class="col-md-12 order-md-last d-flex">
                        <form action="#" class=" p-5 contact-form" method="post" novalidate>
                            <div class="form-group">
                                {% csrf_token %}
                                {{ form.as_p }}
                            </div>
                            <div class="form-group">
                                <input type="submit" value="Register" class="btn btn-primary py-3 px-5">
                                <a href="{% url 'accounts:user_login' %}" class="btn btn-primary py-3 px-5">I have an account!</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

accounts/templates/accounts/verify_code.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="contact-section bg-light">
    <div class="hero-wrap hero-bread" style="background-image: url({% static 'images/bg_7.jpg' %});">
        <div class="container">
            <div class="row no-gutters slider-text align-items-center justify-content-center">
                <div class="col-md-9 ftco-animate text-center">
                    <h1 class="mb-0 bread">Verify Code</h1><br><br>
                    <div class="col-md-12 order-md-last d-flex">
                        <form action="#" class=" p-5 contact-form" method="post" novalidate>
                            <div class="form-group">
                                {% csrf_token %}
                                {{ form.as_p }}
                            </div>
                            <div class="form-group">
                                <input type="submit" value="Verify" class="btn btn-primary py-3 px-5">
<!--back to login and edit phone number-->
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}