A/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('home.urls', namespace='home')),
    path('products/', include('products.urls', namespace='products')),
    path('orders/', include('orders.urls', namespace='orders')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views


app_name = 'orders'
urlpatterns = [
    path('create/', views.OrderCreateView.as_view(), name='order_create'),
    path('detail/<int:order_id>/', views.OrderDetailView.as_view(), name='order_detail'),
    path('delete/<int:order_id>/', views.OrderDeleteView.as_view(), name='order_delete'),
    path('pay/<int:order_id>/', views.OrderPayView.as_view(), name='order_pay'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/add/<int:product_id>/', views.CartAddView.as_view(), name='cart_add'),
    path('cart/remove/<int:product_id>/', views.CartRemoveView.as_view(), name='cart_remove'),
]

products/urls.py
from django.urls import path
from . import views


app_name = 'products'
urlpatterns = [
    path('', views.ProductsView.as_view(), name='products'),
    path('filter/<slug:category_slug>/', views.ProductsView.as_view(), name='category_filter'),
    path('detail/<slug:slug>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('rate/<int:product_id>/<int:rate>/', views.ProductRateView.as_view(), name='product_rate'),
    path('reply/<int:product_id>/<int:comment_id>/', views.ProductCommentReplyView.as_view(),
         name='product_comment_reply'),
]

products/models.py
from django.db import models
from django.urls import reverse
from django.db.models import Avg, Count
from accounts.models import User


class Category(models.Model):
    sub_category = models.ForeignKey(
        'self',
        on_delete=models.CASCADE,
        related_name='subcategory',
        null=True,
        blank=True
    )
    is_sub = models.BooleanField(default=False)
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=100, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('products:category_filter', args=[self.slug])


class Product(models.Model):
    category = models.ManyToManyField(Category, related_name='product')
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=100, unique=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d/')
    price = models.IntegerField()
    description = models.TextField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('products:product_detail', args=[self.slug])

    def rating(self):
        vote = Rating.objects.filter(product=self).aggregate(average=Avg('rate'))
        avg = 0
        if vote['average'] is not None:
            avg = float(vote['average'])
        return avg

    def rate_count(self):
        vote = Rating.objects.filter(product=self).aggregate(count=Count('id'))
        cnt = 0
        if vote['count'] is not None:
            cnt = int(vote['count'])
        return cnt


class Rating(models.Model):
    user = models.ForeignKey(User, models.CASCADE, related_name='user_rate')
    product = models.ForeignKey(Product, models.CASCADE, related_name='product_rete')
    rate = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f'{self.user} - {self.rate} - {self.product.id}'


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_comment')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='product_comment')
    reply = models.ForeignKey('self', on_delete=models.CASCADE, related_name='reply_comment', null=True, blank=True)
    is_reply = models.BooleanField(default=False)
    body = models.TextField(max_length=250)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user} - {self.body[0:20]} - {self.product}'

products/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)
        labels = {'body': False}
        widgets = {
            'body': forms.Textarea(
                attrs={
                    'cols': '30',
                    'rows': '7',
                    'class': 'form-control',
                    'placeholder': 'Comment'
                }
            )
        }


class CommentReplyForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)
        labels = {'body': False}
        widgets = {
            'body': forms.Textarea(
                attrs={
                    'cols': '30',
                    'rows': '7',
                    'class': 'form-control',
                    'placeholder': 'Comment'
                }
            )
        }

products/views.py
from django.core.paginator import Paginator
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from orders.forms import CartAddForm
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from django.utils.decorators import method_decorator
from .forms import CommentForm, CommentReplyForm
from .models import Category, Product, Rating, Comment


class ProductsView(View):
    template_name = 'products/products.html'

    def get(self, request, category_slug=None):
        products = Product.objects.filter(available=True)
        categories = Category.objects.filter(is_sub=True)
        if category_slug:
            # To filter the category
            category = get_object_or_404(Category, slug=category_slug)
            products = products.filter(category=category)
        # Product pagination
        p = Paginator(products, 6)
        page = request.GET.get('page')
        page_products = p.get_page(page)
        return render(request, self.template_name, {
            'categories': categories,
            'page_products': page_products
        })


class ProductDetailView(View):
    form_class = CommentForm
    form_reply_class = CommentReplyForm
    form_cart_add = CartAddForm
    template_name = 'products/product_detail.html'

    def setup(self, request, *args, **kwargs):
        self.product_instance = get_object_or_404(Product, slug=kwargs['slug'])
        return super().setup(self, request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        categories = Category.objects.filter(is_sub=False)
        comments = self.product_instance.product_comment.filter(is_reply=False)
        return render(
            request,
            self.template_name,
            {
                'product': self.product_instance,
                'categories': categories,
                'comments': comments,
                'form': self.form_class,
                'form_reply': self.form_reply_class,
                'form_cart_add': self.form_cart_add
            }
        )

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        # Create a comment
        form = self.form_class(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.user = request.user
            new_comment.product = self.product_instance
            new_comment.save()
            return redirect('products:product_detail', self.product_instance.slug)


class ProductRateView(LoginRequiredMixin, View):
    def get(self, request, product_id, rate):
        product = get_object_or_404(Product, id=product_id)
        rating = Rating.objects.filter(product=product, user=request.user)
        if rate in range(0, 6):
            if rating.exists():
                rating.delete()
                Rating.objects.create(user=request.user, product=product, rate=rate)
            else:
                Rating.objects.create(user=request.user, product=product, rate=rate)
        else:
            return redirect('products:product_detail', product.slug)
        return redirect('products:product_detail', product.slug)


class ProductCommentReplyView(LoginRequiredMixin, View):
    form_class = CommentReplyForm

    def post(self, request, product_id, comment_id):
        product = get_object_or_404(Product, id=product_id)
        comment = get_object_or_404(Comment, id=comment_id)
        form = self.form_class(request.POST)
        if form.is_valid():
            reply = form.save(commit=False)
            reply.user = request.user
            reply.product = product
            reply.reply = comment
            reply.is_reply = True
            reply.save()
        return redirect('products:product_detail', product.slug)

products/templates/products/product_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="ftco-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 mb-5 ftco-animate">
                <a href="images/menu-2.jpg" class="image-popup"><img src="{{ product.image.url }}" class="img-fluid" alt="Colorlib Template"></a>
            </div>
            <div class="col-lg-6 product-details pl-md-5 ftco-animate">
                <h3>{{ product.name }}</h3>
                <div class="rating d-flex">
                    <p class="text-left mr-4">
                        <a href="#" class="mr-2">{{ product.rating|stringformat:".1f" }}</a>
                        <a href="{% url 'products:product_rate' product.id 1 %}"><span class="{% if product.rating > 0.5 %} ion-ios-star {% elif product.rating > 0 %} ion-ios-star-half {% else %} ion-ios-star-outline {% endif %}"></span></a>
                        <a href="{% url 'products:product_rate' product.id 2 %}"><span class="{% if product.rating > 1.5 %} ion-ios-star {% elif product.rating > 1 %} ion-ios-star-half {% else %} ion-ios-star-outline {% endif %}"></span></a>
                        <a href="{% url 'products:product_rate' product.id 3 %}"><span class="{% if product.rating > 2.5 %} ion-ios-star {% elif product.rating > 2 %} ion-ios-star-half {% else %} ion-ios-star-outline {% endif %}"></span></a>
                        <a href="{% url 'products:product_rate' product.id 4 %}"><span class="{% if product.rating > 3.5 %} ion-ios-star {% elif product.rating > 3 %} ion-ios-star-half {% else %} ion-ios-star-outline {% endif %}"></span></a>
                        <a href="{% url 'products:product_rate' product.id 5 %}"><span class="{% if product.rating > 4.5 %} ion-ios-star {% elif product.rating > 4 %} ion-ios-star-half {% else %} ion-ios-star-outline {% endif %}"></span></a>
                    </p>
                    <p class="text-left mr-4">
                    <p class="mr-2" style="color: #000;">{{ product.rate_count }} <span style="color: #bbb;">Rating</span></p>
                </div>
                <p class="price"><span>${{ product.price }}</span></p>
                <p>{{ product.description }}</p><br><br>
                <form action="{% url 'orders:cart_add' product.id %}" method="post" class="col-md-4">
                    {% csrf_token %}
                    {{ form_cart_add }}
                    <br>
                    <input type="submit" value="Add to Cart" class="btn btn-black py-3 px-5">
                </form>
            </div>
        </div>
    </div>
</section>

<section class="ftco-section bg-light">
    <div class="container">
        <div class="row justify-content-center mb-3 pb-3">
            <div class="col-md-12 heading-section text-center ftco-animate">
                <h2 class="mb-4">Related Products</h2>
                <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia</p>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            {% for category in categories %}
            {% for related_product in category.product.all|slice:"1:4" %}
            <div class="col-sm-6 col-md-6 col-lg-3 ftco-animate">
                <div class="product">
                    <a href="{{ related_product.get_absolute_url }}" class="img-prod"><img class="img-fluid" src="{{ related_product.image.url }}" alt="Colorlib Template">
                        <div class="overlay"></div>
                    </a>
                    <div class="text py-3 px-3">
                        <h3><a href="{{ related_product.get_absolute_url }}">{{ related_product.name|truncatewords:2 }}</a></h3>
                        <div class="d-flex">
                            <div class="pricing">
                                <p class="price"><span class="price-sale">${{ related_product.price }}</span></p>
                            </div>
                            <div class="rating">
                                <p class="text-right">
                                    <a href="#"><span class="ion-ios-star"></span>{{ related_product.rating }}</a>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% endfor %}
        </div>
    </div>
</section>

<section class="ftco-section ftco-degree-bg">
    <div class="container">
        <p>
            <a class="btn btn-primary py-2 px-4" data-bs-toggle="collapse" href="#newcomment">Post a comment</a>
        </p>
        <div class="collapse" id="newcomment">
            <div class="col-md-6 order-md-last d-flex">
                <form action="#" method="post" class="bg-white p-0 contact-form" novalidate>
                    <div class="form-group">
                        {% csrf_token %}
                        {{ form }}
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Send" class="btn btn-primary py-2 px-4">
                    </div>
                </form>
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col-lg-8 ftco-animate">
                <h3 class="mb-5">{{ comments.count }} Comments</h3>
                {% for comment in comments %}
                <ul class="comment-list">
                    <li class="comment">
                        <div class="comment-body">
                            <h3>{{ comment.user.full_name }}</h3>
                            <div class="meta">{{ comment.created }}</div>
                            <p>{{ comment.body }}</p>
                            <p>
                                <a class="reply" data-bs-toggle="collapse" href="#{{ comment.id }}" role="button" aria-controls="collapseExample">Reply</a>
                            </p>
                            <div class="collapse" id="{{ comment.id }}">
                                <div class="col-md-6 order-md-last d-flex">
                                    <form action="{% url 'products:product_comment_reply' product.id comment.id %}" method="post" class="bg-white p-0 contact-form" novalidate>
                                        <div class="form-group">
                                            {% csrf_token %}
                                            {{ form_reply }}
                                        </div>
                                        <div class="form-group">
                                            <input type="submit" value="Send" class="btn btn-primary py-2 px-4">
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                        {% with replies=comment.reply_comment.all %}
                        {% for reply in replies %}
                        <ul class="children">
                            <li class="comment">
                                <div class="comment-body">
                                    <h3>{{ reply.user.full_name }}</h3>
                                    <div class="meta">{{ reply.created }}</div>
                                    <p>{{ reply.body }}</p>
                                </div>
                            </li>
                        </ul>
                        {% endfor %}
                        {% endwith %}
                    </li>
                </ul>
                {% empty %}
                <p>No Comments Yet</p>
                {% endfor %}
            </div>
        </div>
    </div>
</section>
{% endblock %}

products/templates/products/products.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="ftco-section bg-light">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-lg-10 order-md-last">
                <div class="row">
                    {% for product in page_products %}
                    <div class="col-sm-6 col-md-6 col-lg-4 ftco-animate">
                        <div class="product">
                            <a href="{{ product.get_absolute_url }}" class="img-prod"><img class="img-fluid" src="{{ product.image.url }}" alt="Colorlib Template">
                                <div class="overlay"></div>
                            </a>
                            <div class="text py-3 px-3">
                                <h3><a href="{{ product.get_absolute_url }}">{{ product.name|truncatewords:3 }}</a></h3>
                                <div class="d-flex">
                                    <div class="pricing">
                                        <p class="price"><span>${{ product.price }}</span></p>
                                    </div>
                                    <div class="rating">
                                        <p class="text-right">
                                            <a href="#"><span class="ion-ios-star"></span>{{ product.rating }}</a>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <div class="row mt-5">
                    <div class="col text-center">
                        <div class="block-27">
                            <ul>
                                {% if page_products.has_previous %}
                                <li><a href="?page={{ page_products.previous_page_number }}">&lt;</a></li>
                                <li><a href="?page=1">1</a></li>
                                {% endif %}
                                <li class="active"><a href="?page={{ page_products.number }}">{{ page_products.number }}</a></li>
                                {% if page_products.has_next %}
                                <li><a href="?page={{ page_products.next_page_number }}">{{ page_products.next_page_number }}</a></li>
                                <li><a href="?page={{ page_products.paginator.num_pages }}">&gt;</a></li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-lg-2 sidebar">
                <div class="sidebar-box-2">
                    {% for category in categories %}
                    <h2 class="heading mb-4"><a href="{{ category.get_absolute_url }}">{{ category.name }}</a></h2>
                    <ul>
                        {% for sub in category.subcategory.all %}
                        <li><a href="{{ sub.get_absolute_url }}">{{ sub.name }}</a></li>
                        {% endfor %}
                    </ul><br>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}