A/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('home.urls', namespace='home')),
    path('products/', include('products.urls', namespace='products')),
    path('orders/', include('orders.urls', namespace='orders')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('verify/', views.UserRegisterVerifyCodeView.as_view(), name='verify_code'),
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('logout/', views.UserLogoutView.as_view(), name='user_logout'),
    path('profile/<int:user_id>', views.UserProfileView.as_view(), name='user_profile'),
]

home/urls.py
from django.urls import path
from . import views


app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('blog/', views.BlogView.as_view(), name='blog'),
    path('single_blog/', views.SingleBlogView.as_view(), name='single_blog'),
    path('about/', views.AboutView.as_view(), name='about'),
]

orders/urls.py
from django.urls import path
from . import views


app_name = 'orders'
urlpatterns = [
    path('create/', views.OrderCreateView.as_view(), name='order_create'),
    path('detail/<int:order_id>/', views.OrderDetailView.as_view(), name='order_detail'),
    path('delete/<int:order_id>/', views.OrderDeleteView.as_view(), name='order_delete'),
    path('pay/<int:order_id>/', views.OrderPayView.as_view(), name='order_pay'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/add/<int:product_id>/', views.CartAddView.as_view(), name='cart_add'),
    path('cart/remove/<int:product_id>/', views.CartRemoveView.as_view(), name='cart_remove'),
]

products/urls.py
from django.urls import path
from . import views


app_name = 'products'
urlpatterns = [
    path('', views.ProductsView.as_view(), name='products'),
    path('filter/<slug:category_slug>/', views.ProductsView.as_view(), name='category_filter'),
    path('detail/<slug:slug>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('rate/<int:product_id>/<int:rate>/', views.ProductRateView.as_view(), name='product_rate'),
    path('reply/<int:product_id>/<int:comment_id>/', views.ProductCommentReplyView.as_view(),
         name='product_comment_reply'),
]

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
    <div class="container">
        <a class="navbar-brand" href="{% url 'home:home' %}">E-Shop</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="oi oi-menu"></span> Menu
        </button>
        <div class="collapse navbar-collapse" id="ftco-nav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active"><a href="{% url 'home:home' %}" class="nav-link">Home</a></li>
                <li class="nav-item"><a href="{% url 'products:products' %}" class="nav-link">Products</a></li>
                <li class="nav-item"><a href="{% url 'home:blog' %}" class="nav-link">Blog</a></li>
                <li class="nav-item"><a href="{% url 'home:about' %}" class="nav-link">About</a></li>
                <li class="nav-item dropdown cta cta-colored">
                    <a class="nav-link dropdown-toggle " href="#" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span class="icon-user"></span></a>
                    <div class="dropdown-menu" aria-labelledby="dropdown04">
                        {% if request.user.is_authenticated %}
                        <a class="dropdown-item" href="{% url 'accounts:user_profile' user.id %}">Profile</a>
                        <a class="dropdown-item" href="{% url 'accounts:user_logout' %}">Logout</a>
                        {% else %}
                        <a class="dropdown-item" href="{% url 'accounts:user_register' %}">Register</a>
                        <a class="dropdown-item" href="{% url 'accounts:user_login' %}">Login</a>
                        {% endif %}
                    </div>
                </li>
                <li class="nav-item cta cta-colored"><a href="{% url 'orders:cart' %}" class="nav-link"><span class="icon-shopping_cart"></span>[{{ cart|length }}]</a></li>
            </ul>
        </div>
    </div>
</nav>